version: "3.9"
services:
  mysqldb:
    image: mysql
    container_name: sql
    env_file: .env
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_USER= $MYSQLDB_USER
        - MYSQL_PASSWORD=$MYSQLDB_USER_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:9000
    depends_on:
      - mysqldb
    env_file: .env
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_USER_PASSWORD=$MYSQLDB_USER

volumes:
  db:
