apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQLDB_USER_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQLDB_USER

            - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: MYSQLDB_USER_PASSWORD

            - name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: MYSQL_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

